import type { CommerceLocale } from './i18n.js';

// AtlasHub's own commercial invoice document (Founder decision: own model for tests; certified issuers
// — NFS-e in Brazil, UK VAT invoice — to be validated). Until then every document carries this notice.
const L: Record<CommerceLocale, Record<string, string>> = {
 'pt-BR': { title: 'Fatura', number: 'Número', issued: 'Emissão', due: 'Vencimento', to: 'Cliente', from: 'Emitente', item: 'Descrição', qty: 'Qtd.', unit: 'Preço unit.', amount: 'Valor', subtotal: 'Subtotal', tax: 'Impostos', total: 'Total', status: 'Estado', draft: 'Rascunho', notice: 'Documento comercial gerado pela AtlasHub para testes. Não substitui a nota fiscal (NFS-e) nem outro documento fiscal.' },
 'pt-PT': { title: 'Fatura', number: 'Número', issued: 'Emissão', due: 'Vencimento', to: 'Cliente', from: 'Emitente', item: 'Descrição', qty: 'Qtd.', unit: 'Preço unit.', amount: 'Valor', subtotal: 'Subtotal', tax: 'Impostos', total: 'Total', status: 'Estado', draft: 'Rascunho', notice: 'Documento comercial gerado pela AtlasHub para testes. Não substitui uma fatura emitida por software certificado.' },
 en: { title: 'Invoice', number: 'Number', issued: 'Issued', due: 'Due', to: 'Bill to', from: 'From', item: 'Description', qty: 'Qty', unit: 'Unit price', amount: 'Amount', subtotal: 'Subtotal', tax: 'Tax', total: 'Total', status: 'Status', draft: 'Draft', notice: 'Commercial document generated by AtlasHub for testing. It does not replace a tax invoice.' },
 es: { title: 'Factura', number: 'Número', issued: 'Emisión', due: 'Vencimiento', to: 'Cliente', from: 'Emisor', item: 'Descripción', qty: 'Cant.', unit: 'Precio unit.', amount: 'Importe', subtotal: 'Subtotal', tax: 'Impuestos', total: 'Total', status: 'Estado', draft: 'Borrador', notice: 'Documento comercial generado por AtlasHub para pruebas. No sustituye a una factura fiscal.' },
 fr: { title: 'Facture', number: 'Numéro', issued: 'Émission', due: 'Échéance', to: 'Client', from: 'Émetteur', item: 'Description', qty: 'Qté', unit: 'Prix unit.', amount: 'Montant', subtotal: 'Sous-total', tax: 'Taxes', total: 'Total', status: 'Statut', draft: 'Brouillon', notice: 'Document commercial généré par AtlasHub à des fins de test. Il ne remplace pas une facture fiscale.' },
};
const esc = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export const money = (minor: number | bigint, currency: string, locale: string) => new Intl.NumberFormat(locale, { style: 'currency', currency }).format(Number(minor) / 100);
const date = (d: Date | null | undefined, locale: string) => d ? new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeZone: 'UTC' }).format(d) : '—';

export interface InvoiceDoc {
 number: string | null; status: string; currency: string; locale: CommerceLocale; issuedAt: Date | null; dueAt: Date | null;
 subtotalMinor: bigint | number; taxMinor: bigint | number; totalMinor: bigint | number;
 issuer: { legalName: string; taxId: string; country: string; address: any; email: string };
 account: { legalName: string; taxId: string | null; country: string; email: string; address: any };
 lines: { description: string; quantity: number; unitMinor: bigint | number; amountMinor: bigint | number }[];
}
const addr = (a: any) => [a?.line1, a?.city, a?.postal_code, a?.country].filter(Boolean).map(esc).join(', ');

export function renderInvoiceHtml(d: InvoiceDoc) {
 const t = L[d.locale]; const m = (v: bigint | number) => money(v, d.currency, d.locale);
 const rows = d.lines.map(l => `<tr><td>${esc(l.description)}</td><td class="n">${l.quantity}</td><td class="n">${m(l.unitMinor)}</td><td class="n">${m(l.amountMinor)}</td></tr>`).join('');
 return `<!doctype html><html lang="${d.locale}"><head><meta charset="utf-8"><title>${t.title} ${esc(d.number ?? t.draft)}</title><style>body{font-family:system-ui,sans-serif;max-width:760px;margin:32px auto;color:#111}table{width:100%;border-collapse:collapse}td,th{padding:6px;border-bottom:1px solid #ddd;text-align:left}.n{text-align:right}.notice{margin-top:24px;font-size:12px;color:#555}</style></head><body>
<h1>${t.title} ${esc(d.number ?? t.draft)}</h1>
<p><b>${t.status}:</b> ${esc(d.status)} · <b>${t.issued}:</b> ${date(d.issuedAt, d.locale)} · <b>${t.due}:</b> ${date(d.dueAt, d.locale)}</p>
<p><b>${t.from}:</b> ${esc(d.issuer.legalName)} (${esc(d.issuer.taxId)}) — ${addr(d.issuer.address)} — ${esc(d.issuer.email)}</p>
<p><b>${t.to}:</b> ${esc(d.account.legalName)}${d.account.taxId ? ` (${esc(d.account.taxId)})` : ''} — ${addr(d.account.address)} — ${esc(d.account.email)}</p>
<table><thead><tr><th>${t.item}</th><th class="n">${t.qty}</th><th class="n">${t.unit}</th><th class="n">${t.amount}</th></tr></thead><tbody>${rows}</tbody>
<tfoot><tr><td colspan="3" class="n">${t.subtotal}</td><td class="n">${m(d.subtotalMinor)}</td></tr><tr><td colspan="3" class="n">${t.tax}</td><td class="n">${m(d.taxMinor)}</td></tr><tr><td colspan="3" class="n"><b>${t.total}</b></td><td class="n"><b>${m(d.totalMinor)}</b></td></tr></tfoot></table>
<p class="notice">${t.notice}</p></body></html>`;
}

export function invoiceNumber(series: string, year: number, n: number) { return `${series}-${year}-${String(n).padStart(6, '0')}`; }
