-- Phase B: commercial platform (catalog, CRM, concierge, commerce, billing). See docs/DATA-MODEL-v2.md.
-- Domain prefixes instead of separate schemas (Prisma compatibility); same RLS model as Round 1/2.
-- Money: BIGINT minor units + ISO 4217 currency. Locales: pt-BR, pt-PT, en, es, fr.

-- ===== Global catalogue (platform-owned, read-only at runtime) =====
CREATE TABLE "catalog_mission_template" ("id" TEXT PRIMARY KEY, "roleId" TEXT NOT NULL REFERENCES "Role"(id), "kind" TEXT NOT NULL CHECK ("kind" IN ('standard','modular')), "durationDays" INTEGER, "capacity" JSONB NOT NULL, "includedAddons" TEXT[] NOT NULL DEFAULT '{}', "optionalAddons" TEXT[] NOT NULL DEFAULT '{}', "status" TEXT NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','active','retired')));
CREATE TABLE "catalog_mission_template_i18n" ("templateId" TEXT NOT NULL REFERENCES "catalog_mission_template"(id), "locale" TEXT NOT NULL CHECK ("locale" IN ('pt-BR','pt-PT','en','es','fr')), "name" TEXT NOT NULL, "objective" TEXT NOT NULL, "scopeIn" TEXT NOT NULL, "scopeOut" TEXT NOT NULL, PRIMARY KEY ("templateId","locale"));
CREATE TABLE "catalog_product" ("id" TEXT PRIMARY KEY, "kind" TEXT NOT NULL CHECK ("kind" IN ('mission','subscription','addon','setup','credit_pack')), "roleId" TEXT REFERENCES "Role"(id), "templateId" TEXT REFERENCES "catalog_mission_template"(id), "status" TEXT NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','active','retired')), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "catalog_product_i18n" ("productId" TEXT NOT NULL REFERENCES "catalog_product"(id), "locale" TEXT NOT NULL CHECK ("locale" IN ('pt-BR','pt-PT','en','es','fr')), "name" TEXT NOT NULL, "description" TEXT NOT NULL, PRIMARY KEY ("productId","locale"));
-- Prices are 'draft' until the Founder approves them; only 'active' prices are ever shown or charged.
CREATE TABLE "catalog_price" ("id" TEXT PRIMARY KEY, "productId" TEXT NOT NULL REFERENCES "catalog_product"(id), "currency" TEXT NOT NULL CHECK ("currency" IN ('BRL','EUR','USD')), "pricingModel" TEXT NOT NULL CHECK ("pricingModel" IN ('flat','per_seat','per_unit','tiered','package','mission_fixed','custom')), "interval" TEXT NOT NULL CHECK ("interval" IN ('one_time','month','quarter','year')), "amountMinor" BIGINT CHECK ("amountMinor" >= 0), "includedQuantity" INTEGER, "overageMinor" BIGINT, "usageMetric" TEXT, "trialDays" INTEGER CHECK ("trialDays" IN (3,7)), "market" TEXT NOT NULL DEFAULT '*', "taxBehavior" TEXT NOT NULL DEFAULT 'exclusive' CHECK ("taxBehavior" IN ('inclusive','exclusive')), "status" TEXT NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','active','retired')), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "catalog_price_product_idx" ON "catalog_price"("productId","currency","status");
-- Legal entities that sell: UK holding (international) and the Brazilian CNPJ (BR customers).
CREATE TABLE "billing_issuer" ("id" TEXT PRIMARY KEY, "legalName" TEXT NOT NULL, "country" TEXT NOT NULL, "taxId" TEXT NOT NULL, "address" JSONB NOT NULL, "currencies" TEXT[] NOT NULL, "series" TEXT NOT NULL UNIQUE, "email" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'active');
CREATE TABLE "billing_invoice_sequence" ("issuerId" TEXT NOT NULL REFERENCES "billing_issuer"(id), "year" INTEGER NOT NULL, "last" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("issuerId","year"));

-- ===== CRM (tenant-scoped; the AtlasHub house tenant holds AtlasHub's own pipeline) =====
CREATE TABLE "crm_company" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "name" TEXT NOT NULL, "domain" TEXT, "country" TEXT, "taxId" TEXT, "sizeBand" TEXT, "industry" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"));
CREATE UNIQUE INDEX "crm_company_domain_key" ON "crm_company"("tenantId","domain") WHERE "domain" IS NOT NULL;
CREATE TABLE "crm_contact" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "companyId" TEXT, "fullName" TEXT NOT NULL, "emailNorm" TEXT, "phoneE164" TEXT, "preferredLocale" TEXT NOT NULL DEFAULT 'pt-BR', "timezone" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"), FOREIGN KEY ("tenantId","companyId") REFERENCES "crm_company"("tenantId",id));
CREATE UNIQUE INDEX "crm_contact_email_key" ON "crm_contact"("tenantId","emailNorm") WHERE "emailNorm" IS NOT NULL;
CREATE UNIQUE INDEX "crm_contact_phone_key" ON "crm_contact"("tenantId","phoneE164") WHERE "phoneE164" IS NOT NULL;
CREATE TABLE "crm_consent" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "contactId" TEXT NOT NULL, "purpose" TEXT NOT NULL CHECK ("purpose" IN ('contact_sales','marketing','whatsapp','data_processing','trial')), "lawfulBasis" TEXT NOT NULL CHECK ("lawfulBasis" IN ('consent','legitimate_interest','contract')), "source" TEXT NOT NULL, "textVersion" TEXT NOT NULL, "locale" TEXT NOT NULL, "grantedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "withdrawnAt" TIMESTAMP(3), "evidence" JSONB NOT NULL, FOREIGN KEY ("tenantId","contactId") REFERENCES "crm_contact"("tenantId",id));
CREATE TABLE "crm_suppression" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "kind" TEXT NOT NULL CHECK ("kind" IN ('email','phone','domain')), "valueHash" TEXT NOT NULL, "reason" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","kind","valueHash"));
CREATE TABLE "concierge_session" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "channel" TEXT NOT NULL, "agent" TEXT NOT NULL, "locale" TEXT NOT NULL, "aiDisclosed" BOOLEAN NOT NULL, "qualification" JSONB NOT NULL DEFAULT '{}', "leadId" TEXT, "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"));
CREATE TABLE "crm_lead" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "contactId" TEXT NOT NULL, "companyId" TEXT, "source" TEXT NOT NULL CHECK ("source" IN ('site','simulator','clara','import','api','referral','event','partner','ads')), "stage" TEXT NOT NULL DEFAULT 'new' CHECK ("stage" IN ('new','contacted','qualified','simulation','trial_requested','trial_active','proposal_sent','negotiation','won','lost','nurture')), "score" INTEGER NOT NULL DEFAULT 0, "fit" JSONB NOT NULL DEFAULT '{}', "interestRoles" TEXT[] NOT NULL DEFAULT '{}', "locale" TEXT NOT NULL, "utm" JSONB NOT NULL DEFAULT '{}', "conciergeSessionId" TEXT, "lostReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"), FOREIGN KEY ("tenantId","contactId") REFERENCES "crm_contact"("tenantId",id), FOREIGN KEY ("tenantId","companyId") REFERENCES "crm_company"("tenantId",id));
CREATE INDEX "crm_lead_stage_idx" ON "crm_lead"("tenantId","stage","updatedAt");
CREATE TABLE "crm_activity" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "leadId" TEXT, "kind" TEXT NOT NULL, "note" TEXT NOT NULL, "actor" TEXT NOT NULL, "at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("tenantId","leadId") REFERENCES "crm_lead"("tenantId",id));
CREATE INDEX "crm_activity_lead_idx" ON "crm_activity"("tenantId","leadId","at");
CREATE TABLE "crm_import_batch" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "source" TEXT NOT NULL, "lawfulBasis" TEXT NOT NULL CHECK ("lawfulBasis" IN ('consent','legitimate_interest','contract')), "basisNote" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'validated' CHECK ("status" IN ('validated','imported','discarded')), "rowsTotal" INTEGER NOT NULL, "rowsValid" INTEGER NOT NULL, "rowsDuplicate" INTEGER NOT NULL, "rowsRejected" INTEGER NOT NULL, "rowsSuppressed" INTEGER NOT NULL, "createdBy" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"));
CREATE TABLE "crm_import_row" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "batchId" TEXT NOT NULL, "rowNo" INTEGER NOT NULL, "normalized" JSONB NOT NULL, "errors" TEXT[] NOT NULL DEFAULT '{}', "outcome" TEXT NOT NULL CHECK ("outcome" IN ('valid','duplicate','rejected','suppressed','imported')), "leadId" TEXT, FOREIGN KEY ("tenantId","batchId") REFERENCES "crm_import_batch"("tenantId",id));

-- ===== Commerce =====
CREATE TABLE "commerce_trial" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "leadId" TEXT NOT NULL, "templateId" TEXT NOT NULL REFERENCES "catalog_mission_template"(id), "days" INTEGER NOT NULL CHECK ("days" IN (3,7)), "status" TEXT NOT NULL DEFAULT 'requested' CHECK ("status" IN ('requested','approved','active','expired','converted','declined')), "customerTenantId" TEXT REFERENCES "Tenant"(id), "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "approvedAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3), FOREIGN KEY ("tenantId","leadId") REFERENCES "crm_lead"("tenantId",id));
CREATE TABLE "commerce_quote" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "leadId" TEXT NOT NULL, "issuerId" TEXT NOT NULL REFERENCES "billing_issuer"(id), "status" TEXT NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','sent','accepted','expired','rejected')), "currency" TEXT NOT NULL CHECK ("currency" IN ('BRL','EUR','USD')), "locale" TEXT NOT NULL, "totalMinor" BIGINT NOT NULL DEFAULT 0, "validUntil" TIMESTAMP(3) NOT NULL, "termsVersion" TEXT NOT NULL, "acceptTokenHash" TEXT UNIQUE, "acceptedAt" TIMESTAMP(3), "acceptedBy" TEXT, "customerTenantId" TEXT REFERENCES "Tenant"(id), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"), FOREIGN KEY ("tenantId","leadId") REFERENCES "crm_lead"("tenantId",id));
CREATE TABLE "commerce_quote_line" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "quoteId" TEXT NOT NULL, "priceId" TEXT NOT NULL REFERENCES "catalog_price"(id), "quantity" INTEGER NOT NULL CHECK ("quantity" > 0), "unitMinor" BIGINT NOT NULL, "amountMinor" BIGINT NOT NULL, "description" TEXT NOT NULL, FOREIGN KEY ("tenantId","quoteId") REFERENCES "commerce_quote"("tenantId",id));
CREATE TABLE "commerce_order" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "quoteId" TEXT, "status" TEXT NOT NULL DEFAULT 'pending_payment' CHECK ("status" IN ('pending_payment','paid','fulfilling','fulfilled','cancelled')), "currency" TEXT NOT NULL, "totalMinor" BIGINT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"));
CREATE TABLE "commerce_subscription" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "orderId" TEXT, "priceId" TEXT NOT NULL REFERENCES "catalog_price"(id), "quantity" INTEGER NOT NULL DEFAULT 1, "status" TEXT NOT NULL DEFAULT 'incomplete' CHECK ("status" IN ('incomplete','trialing','active','past_due','paused','cancelled','ended')), "currentPeriodStart" TIMESTAMP(3), "currentPeriodEnd" TIMESTAMP(3), "cancelAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("tenantId","orderId") REFERENCES "commerce_order"("tenantId",id));
-- What a payment or a trial unlocks. Activating a digital employee in production stays a human gate.
CREATE TABLE "commerce_entitlement" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "key" TEXT NOT NULL, "source" TEXT NOT NULL CHECK ("source" IN ('order','subscription','trial','grant')), "sourceId" TEXT NOT NULL, "quantity" INTEGER, "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "validUntil" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'active' CHECK ("status" IN ('active','expired','revoked')), UNIQUE ("tenantId","key","source","sourceId"));
CREATE TABLE "commerce_mission" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "templateId" TEXT NOT NULL REFERENCES "catalog_mission_template"(id), "kind" TEXT NOT NULL CHECK ("kind" IN ('standard','modular')), "addons" TEXT[] NOT NULL DEFAULT '{}', "capacity" JSONB NOT NULL, "source" TEXT NOT NULL CHECK ("source" IN ('trial','order')), "sourceId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'provisioning' CHECK ("status" IN ('provisioning','sandbox','acceptance','active','paused','completed','cancelled','terminated')), "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3), "deploymentId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","source","sourceId","templateId"));

-- ===== Billing =====
CREATE TABLE "billing_account" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL UNIQUE REFERENCES "Tenant"(id), "issuerId" TEXT NOT NULL REFERENCES "billing_issuer"(id), "legalName" TEXT NOT NULL, "taxId" TEXT, "country" TEXT NOT NULL, "email" TEXT NOT NULL, "address" JSONB NOT NULL DEFAULT '{}', "currency" TEXT NOT NULL CHECK ("currency" IN ('BRL','EUR','USD')), "locale" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"));
CREATE TABLE "billing_invoice" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "accountId" TEXT NOT NULL, "issuerId" TEXT NOT NULL REFERENCES "billing_issuer"(id), "orderId" TEXT, "number" TEXT UNIQUE, "status" TEXT NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','open','paid','void','uncollectible')), "currency" TEXT NOT NULL CHECK ("currency" IN ('BRL','EUR','USD')), "subtotalMinor" BIGINT NOT NULL, "taxMinor" BIGINT NOT NULL, "totalMinor" BIGINT NOT NULL, "locale" TEXT NOT NULL, "issuedAt" TIMESTAMP(3), "dueAt" TIMESTAMP(3), "paidAt" TIMESTAMP(3), "legalDocumentRef" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("tenantId","id"), FOREIGN KEY ("tenantId","accountId") REFERENCES "billing_account"("tenantId",id), FOREIGN KEY ("tenantId","orderId") REFERENCES "commerce_order"("tenantId",id));
CREATE TABLE "billing_invoice_line" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "invoiceId" TEXT NOT NULL, "priceId" TEXT REFERENCES "catalog_price"(id), "description" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "unitMinor" BIGINT NOT NULL, "taxRateBp" INTEGER NOT NULL DEFAULT 0, "amountMinor" BIGINT NOT NULL, FOREIGN KEY ("tenantId","invoiceId") REFERENCES "billing_invoice"("tenantId",id));
CREATE TABLE "billing_payment" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "invoiceId" TEXT NOT NULL, "provider" TEXT NOT NULL CHECK ("provider" IN ('sandbox','mercadopago','stripe','stone','picpay')), "providerRef" TEXT, "method" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending','succeeded','failed','refunded','disputed','expired')), "amountMinor" BIGINT NOT NULL, "currency" TEXT NOT NULL, "checkout" JSONB NOT NULL DEFAULT '{}', "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("provider","providerRef"), FOREIGN KEY ("tenantId","invoiceId") REFERENCES "billing_invoice"("tenantId",id));
CREATE TABLE "billing_delivery" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL REFERENCES "Tenant"(id), "invoiceId" TEXT NOT NULL, "channel" TEXT NOT NULL CHECK ("channel" IN ('email','whatsapp','portal')), "recipient" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'queued' CHECK ("status" IN ('queued','sent','failed','skipped')), "attempts" INTEGER NOT NULL DEFAULT 0, "lastError" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "sentAt" TIMESTAMP(3), FOREIGN KEY ("tenantId","invoiceId") REFERENCES "billing_invoice"("tenantId",id));
-- Provider webhooks arrive before the tenant is known: stored once per (provider, event), processed by the worker
-- only after the payment is re-read from the provider (or the sandbox ledger) — never from the payload alone.
CREATE TABLE "billing_webhook_event" ("id" TEXT PRIMARY KEY, "provider" TEXT NOT NULL, "eventId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "providerRef" TEXT, "payloadSha256" TEXT NOT NULL, "facts" JSONB NOT NULL DEFAULT '{}', "status" TEXT NOT NULL DEFAULT 'received' CHECK ("status" IN ('received','processed','ignored','failed')), "attempts" INTEGER NOT NULL DEFAULT 0, "error" TEXT, "tenantId" TEXT REFERENCES "Tenant"(id), "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedAt" TIMESTAMP(3), UNIQUE ("provider","eventId"));

-- ===== Access control =====
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['catalog_mission_template','catalog_mission_template_i18n','catalog_product','catalog_product_i18n','catalog_price','billing_issuer'] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
  EXECUTE format('REVOKE ALL ON %I FROM PUBLIC', t);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE ON %I TO waas_runtime', t);
  EXECUTE format('CREATE POLICY catalogue_read ON %I FOR SELECT TO waas_runtime USING (true)', t);
  EXECUTE format('CREATE POLICY platform_write ON %I FOR ALL TO waas_runtime USING (waas_scope() = ''platform'') WITH CHECK (waas_scope() = ''platform'')', t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['crm_company','crm_contact','crm_consent','crm_suppression','concierge_session','crm_lead','crm_activity','crm_import_batch','crm_import_row','commerce_trial','commerce_quote','commerce_quote_line','commerce_order','commerce_subscription','commerce_entitlement','commerce_mission','billing_account','billing_invoice','billing_invoice_line','billing_payment','billing_delivery'] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
  EXECUTE format('REVOKE ALL ON %I FROM PUBLIC', t);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON %I TO waas_runtime', t);
  EXECUTE format('CREATE POLICY tenant_isolation ON %I FOR ALL TO waas_runtime USING ("tenantId" = waas_tenant()) WITH CHECK ("tenantId" = waas_tenant())', t);
  EXECUTE format('CREATE POLICY platform_operator ON %I FOR ALL TO waas_runtime USING (waas_scope() = ''platform'') WITH CHECK (waas_scope() = ''platform'')', t);
 END LOOP;
 FOREACH t IN ARRAY ARRAY['catalog_mission_template','catalog_mission_template_i18n','catalog_product','catalog_product_i18n','catalog_price','billing_issuer','billing_invoice_sequence','crm_company','crm_contact','crm_consent','crm_suppression','concierge_session','crm_lead','crm_activity','crm_import_batch','crm_import_row','commerce_trial','commerce_quote','commerce_quote_line','commerce_order','commerce_subscription','commerce_entitlement','commerce_mission','billing_account','billing_invoice','billing_invoice_line','billing_payment','billing_delivery','billing_webhook_event'] LOOP
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN EXECUTE format('REVOKE ALL ON %I FROM anon', t); END IF;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN EXECUTE format('REVOKE ALL ON %I FROM authenticated', t); END IF;
 END LOOP;
END $$;
-- Invoice numbering: gap-free per issuer and year; the row lock serialises concurrent issuing.
ALTER TABLE "billing_invoice_sequence" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "billing_invoice_sequence" FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON "billing_invoice_sequence" TO waas_runtime;
CREATE POLICY numbering ON "billing_invoice_sequence" FOR ALL TO waas_runtime USING (waas_scope() IN ('platform','billing') OR waas_tenant() IS NOT NULL) WITH CHECK (waas_scope() IN ('platform','billing') OR waas_tenant() IS NOT NULL);
-- Webhook inbox: written by the webhook endpoint scope, processed by the worker.
ALTER TABLE "billing_webhook_event" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON "billing_webhook_event" FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON "billing_webhook_event" TO waas_runtime;
CREATE POLICY webhook_inbox ON "billing_webhook_event" FOR ALL TO waas_runtime USING (waas_scope() IN ('billing_webhook','worker','platform')) WITH CHECK (waas_scope() IN ('billing_webhook','worker','platform'));
-- Narrow pre-tenant lookups (read only).
CREATE POLICY payment_resolve ON "billing_payment" FOR SELECT TO waas_runtime USING (waas_scope() IN ('billing_webhook','worker'));
CREATE POLICY quote_accept_resolve ON "commerce_quote" FOR SELECT TO waas_runtime USING (waas_scope() = 'quote_accept');
CREATE POLICY trial_expiry ON "commerce_trial" FOR SELECT TO waas_runtime USING (waas_scope() = 'worker');
