import test from 'node:test';import assert from 'node:assert/strict';import {SignJWT} from 'jose';import pg from 'pg';import {randomUUID} from 'node:crypto';
const base='http://127.0.0.1:4000';const owner=new pg.Client({connectionString:process.env.DATABASE_URL});await owner.connect();
const runtime=new pg.Client({connectionString:process.env.APP_DATABASE_URL});await runtime.connect();
const ids=['A','B'].map(()=>randomUUID());
for(const [i,t] of ['tenant-A','tenant-B'].entries())await owner.query('INSERT INTO "Project"(id,"tenantId",slug,name,status) VALUES ($1,$2,$3,$4,$5)',[ids[i],t,'probe-'+ids[i],'Synthetic project','sandbox']);
async function req(path,sub='admin-A',method='GET',body){const token=await new SignJWT({}).setProtectedHeader({alg:'HS256'}).setSubject(sub).setIssuer(process.env.JWT_ISSUER).setAudience(process.env.JWT_AUDIENCE).setExpirationTime('5m').sign(new TextEncoder().encode(process.env.STAGING_JWT_SECRET));return fetch(base+path,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
test('all Workspaces reads require authentication',async()=>{for(const p of ['/v1/projects','/v1/expert','/v1/usage/summary','/v1/roles'])assert.equal((await fetch(base+p)).status,401);});
test('Projects isolates A/B and does not expose deployment configuration',async()=>{const r=await req('/v1/projects?tenant=tenant-A');assert.equal(r.status,200);const rows=await r.json();assert.ok(rows.some(p=>p.id===ids[0]));assert.ok(rows.every(p=>p.tenantId==='tenant-A'&&p.id!==ids[1]));assert.equal((await req('/v1/projects?tenant=tenant-B')).status,403);assert.ok(rows.every(p=>!('config' in p)));});
test('Expert is honestly unprovisioned and tenant-scoped',async()=>{const r=await req('/v1/expert?tenant=tenant-A');assert.equal(r.status,200);assert.equal((await r.json()).enabled,false);assert.equal((await req('/v1/expert?tenant=tenant-B')).status,403);});
test('Usage uses bounded half-open intervals and segregates tenants',async()=>{const q='&from=2026-01-01T00:00:00Z&to=2027-01-01T00:00:00Z';const r=await req('/v1/usage/summary?tenant=tenant-A'+q);assert.equal(r.status,200);const b=await r.json();assert.ok(Array.isArray(b.metrics));assert.equal((await req('/v1/usage/summary?tenant=tenant-B'+q)).status,403);assert.equal((await req('/v1/usage/summary?tenant=tenant-A')).status,400);});
test('project admin is authenticated and forbidden to tenant admins',async()=>{assert.equal((await fetch(base+'/v1/ops/projects',{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).status,401);assert.equal((await req('/v1/ops/projects','admin-A','POST',{tenant:'tenant-A',slug:'probe',name:'Synthetic'})).status,403);});
test('Project RLS blocks cross-tenant writes and deployment links',async()=>{await runtime.query('BEGIN');try{await runtime.query("SELECT set_config('app.tenant_id','tenant-A',true)");const r=await runtime.query('SELECT id FROM "Project"');assert.ok(r.rows.every(p=>p.id!==ids[1]));await assert.rejects(runtime.query('INSERT INTO "Project"(id,"tenantId",slug,name) VALUES ($1,$2,$3,$4)',[randomUUID(),'tenant-B','forbidden','Synthetic']),e=>e.code==='42501');}finally{await runtime.query('ROLLBACK');}
await owner.query('BEGIN');try{await assert.rejects(owner.query('UPDATE "Deployment" SET "projectId"=$1 WHERE "tenantId"=$2',[ids[1],'tenant-A']),e=>e.code==='23503');}finally{await owner.query('ROLLBACK');}});
test.after(async()=>{await owner.query('DELETE FROM "Project" WHERE id=ANY($1::text[])',[ids]);await owner.end();await runtime.end();});
