// Generates docs/ROLES.md from the role registry (run after `npm run build`). Do not edit the output by hand.
import {writeFileSync} from 'node:fs';import {ROLES,ROLE_BINDINGS} from '../dist/packages/roles/index.js';
const policy={auto:'automática',approval:'**aprovação humana**',forbidden:'❌ proibida'};
let md=`# Colaboradores digitais — registo técnico\n\n> Gerado por \`scripts/roles-doc.mjs\` a partir de \`packages/roles\`. Não editar à mão.\n\nTodos os colaboradores correm no mesmo motor: inbound assinado → tenant pelo canal → classificação de intenção (regras pt/en/es; IA opcional só para mensagens não reconhecidas) → playbook determinístico → gateway de tools (grant + schema + política) → sistema do cliente (sandbox em staging, ou n8n por tool) → aprovação humana quando exigida → auditoria, uso e custo.\n\n| Role | Pack | Intenções | Tools com aprovação | Tools proibidas |\n|---|---|---|---|---|\n| ROLE-001 Rececionista Digital | PACK-001 | confirm, reschedule, clinical, unknown | agenda.update_status (remarcação) | aconselhamento clínico |\n`;
for(const r of Object.values(ROLES)){const t=Object.entries(r.tools);md+=`| ${r.id} ${r.name['pt-PT']} | ${r.packId} | ${r.intents.map(i=>i.id).join(', ')} | ${t.filter(([,s])=>s.policy==='approval').map(([id])=>id).join(', ')||'—'} | ${t.filter(([,s])=>s.policy==='forbidden').map(([id])=>id).join(', ')||'—'} |\n`;}
for(const r of Object.values(ROLES)){
 md+=`\n## ${r.id} — ${r.name['pt-PT']} (${r.packId} \`${r.packSlug}\` v${r.version})\n\nLínguas: pt-PT, pt-BR, en, es.${r.sensitiveKeys?` Atributos removidos à entrada: ${r.sensitiveKeys.length} (ex.: ${r.sensitiveKeys.slice(0,6).join(', ')}).`:''}\n\n| Tool | Política | Efeito externo | Rota n8n (quando ativada por deployment) |\n|---|---|---|---|\n`;
 for(const [id,s] of Object.entries(r.tools))md+=`| \`${id}\` | ${policy[s.policy]} | ${s.effect?'sim (idempotente por run)':'não'} | ${s.policy==='forbidden'?'—':`\`POST /webhook/${r.packSlug}/${id.replace('.','-')}\``} |\n`;
 md+=`\nTools concedidas no provisionamento: ${ROLE_BINDINGS[r.id].tools.map(x=>`\`${x}\``).join(', ')}.\n`;
}
md+=`\n## Contrato n8n\n\nPedido: \`POST {N8N_BASE_URL}/webhook/<pack>/<tool>\` com corpo \`{identity:{tenantId,deploymentId,runId},tool,input,timestamp}\`, cabeçalhos \`Idempotency-Key: <runId>:<tool>\` e \`X-Atlas-Signature\` (HMAC-SHA256 do corpo com \`N8N_SIGNING_SECRET\`). Só HTTPS, timeout \`N8N_TIMEOUT_MS\` (5 s), sem redirects. Resposta: objeto JSON. O workflow tem de verificar a assinatura, rejeitar timestamps com mais de 5 minutos e tratar a chave de idempotência.\n`;
writeFileSync('docs/ROLES.md',md);console.log('docs/ROLES.md written');
